

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dex 014
 */
public class mainFrame extends javax.swing.JFrame {

    private File wppath;
    private String workplace;
    private ArrayList<AndroidRec> andrec = new ArrayList<AndroidRec>();
    private ArrayList<Image> images = new ArrayList<Image>();
    private ArrayList<session> ses = new ArrayList<session>();
    private ArrayList<mod_log> log = new ArrayList<mod_log>();
    private ArrayList<all_log> reftable;// = new ArrayList<all_log>();
    private ArrayList<pagedetail> page = new ArrayList<pagedetail>();
    private ArrayList<userdetail> user = new ArrayList<userdetail>(); 
    private JTable[] tables = new JTable[4];
    private Image[] animeimg = new Image[100];
    private boolean fromzip = false;
    private JTable viewtable;
    private DefaultTableModel tableModel;
    //
    private ArrayList<mobileact> mobact = new ArrayList<mobileact>();
    private ArrayList<mobiletab> mobtab = new ArrayList<mobiletab>();
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        try {
            setDir();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        lab_android.setText("Android not read");
        lab_moodle.setText("Moodle not read");
        
    }

    /*
     * set working place path
     * if set before, read path
     */
    public void setDir() throws FileNotFoundException, IOException{
        final JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Choose Workplace Dirtory");
        FileSystemView fsv = FileSystemView.getFileSystemView();
        //wppath stores workplace location
        wppath = fsv.getDefaultDirectory();
        File rd = new File(wppath.getAbsolutePath() + "/USQ_Reporter.txt");
        int ext = 0;
        if(rd.exists())ext=1;
        if(!rd.exists())ext=2;
        FileReader fr; 
        if(rd.exists()){
            fr= new FileReader(rd);
            if(fr.read()==-1)
                ext=2;
        }
        //System.out.println(ext);
        //workplace path
        if(ext==1) {
            BufferedReader br = new BufferedReader(new FileReader(rd));
            workplace = br.readLine();
        }else if (ext==2) {
            jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int returnVal = jfc.showOpenDialog(this);
            
            if(returnVal == JFileChooser.APPROVE_OPTION) {
                File file = jfc.getSelectedFile();
                if(!file.exists()) {
                    JOptionPane.showMessageDialog(null, "file doesn't exist.", "System Message", JOptionPane.ERROR_MESSAGE);
                } else if(file.isDirectory()) {
                    workplace = file.getAbsolutePath();
                }
            }
            BufferedWriter bw = new BufferedWriter(new FileWriter(rd));
            bw.write(workplace);
            bw.flush();
            bw.close();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	//UI design
        contentPane = new javax.swing.JPanel();
        pane_fileState = new javax.swing.JPanel();
        lab_fileState = new javax.swing.JLabel();
        lab_android = new javax.swing.JLabel();
        lab_moodle = new javax.swing.JLabel();
        pane_graphic = new javax.swing.JPanel();
        combox_graphic = new javax.swing.JComboBox();
        lab_graphic = new javax.swing.JLabel();
        btn_view = new javax.swing.JButton();
        ck_ip = new javax.swing.JCheckBox();
        ck_bt = new javax.swing.JCheckBox();
        ck_st = new javax.swing.JCheckBox();
        btn_viewimage = new javax.swing.JButton();
        pane_buttons = new javax.swing.JPanel();
        btn_readFile = new javax.swing.JButton();
        btn_export = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        pane_canvas = new javax.swing.JScrollPane();
        pane_fileList = new javax.swing.JScrollPane();
        animetable = new javax.swing.JTable();
        topMenuBar = new javax.swing.JMenuBar();
        topMenu_1 = new javax.swing.JMenu();
        tpm1_menuItem2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pane_fileState.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lab_fileState.setText("File State");

        lab_android.setText("Android Read In");

        lab_moodle.setText("Moodle Read In");

        javax.swing.GroupLayout pane_fileStateLayout = new javax.swing.GroupLayout(pane_fileState);
        pane_fileState.setLayout(pane_fileStateLayout);
        pane_fileStateLayout.setHorizontalGroup(
            pane_fileStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fileStateLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pane_fileStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lab_fileState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lab_android, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(lab_moodle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pane_fileStateLayout.setVerticalGroup(
            pane_fileStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_fileStateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lab_fileState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab_android, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lab_moodle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_graphic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        combox_graphic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Log", "User", "Webpage", "User Act"}));
        combox_graphic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combox_graphicItemStateChanged(evt);
            }
        });

        lab_graphic.setText("Choose display option");

        btn_view.setText("View Table");
        btn_view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewMouseClicked(evt);
            }
        });

        ck_ip.setText("IP");

        ck_bt.setText("Browser type");

        ck_st.setText("System type");

        btn_viewimage.setText("View Image");
        btn_viewimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_viewimageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pane_graphicLayout = new javax.swing.GroupLayout(pane_graphic);
        pane_graphic.setLayout(pane_graphicLayout);
        pane_graphicLayout.setHorizontalGroup(
            pane_graphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_graphicLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pane_graphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combox_graphic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lab_graphic, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addGroup(pane_graphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_graphicLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(ck_ip)
                        .addGap(55, 55, 55)
                        .addComponent(ck_bt)
                        .addGap(18, 18, 18)
                        .addComponent(ck_st)
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(pane_graphicLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_viewimage, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        pane_graphicLayout.setVerticalGroup(
            pane_graphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_graphicLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pane_graphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_graphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ck_bt)
                        .addComponent(ck_st)
                        .addComponent(ck_ip))
                    .addComponent(lab_graphic, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pane_graphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combox_graphic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pane_graphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_viewimage, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pane_buttons.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_readFile.setText("Read Files");
        btn_readFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_readFileMouseClicked(evt);
            }
        });

        btn_export.setText("Export");
        btn_export.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exportMouseClicked(evt);
            }
        });

        btn_clear.setText("Clear Data");
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clearMouseClicked(evt);
            }
        });

        btn_exit.setText("Exit");
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pane_buttonsLayout = new javax.swing.GroupLayout(pane_buttons);
        pane_buttons.setLayout(pane_buttonsLayout);
        pane_buttonsLayout.setHorizontalGroup(
            pane_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_export, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_readFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 28, Short.MAX_VALUE)
                .addGroup(pane_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pane_buttonsLayout.setVerticalGroup(
            pane_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_buttonsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pane_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btn_readFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pane_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_export, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_canvas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        animetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        
        pane_fileList.setViewportView(animetable);

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_fileList, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pane_fileState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addComponent(pane_graphic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pane_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(contentPaneLayout.createSequentialGroup()
                        .addComponent(pane_canvas)
                        .addContainerGap())))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane_canvas, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pane_fileList, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pane_graphic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pane_fileState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pane_buttons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        topMenu_1.setText("File");

        tpm1_menuItem2.setText("Exit");
        tpm1_menuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpm1_menuItem2MouseClicked(evt);
            }
        });
        topMenu_1.add(tpm1_menuItem2);

        topMenuBar.add(topMenu_1);

        setJMenuBar(topMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // exit clicked
        System.exit(0);
    }                                     

    //clear data button
    private void btn_clearMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // clear data clicked
        andrec.clear();
        ses.clear();
        images.clear();
        log.clear();
        if(reftable == null){}else{reftable.clear();}
        fromzip = false;
        page.clear();
        user.clear();
        tables = new JTable[4];
        lab_android.setText("Android not read");
        lab_moodle.setText("Moodle not read");
        animeimg = new Image[100];
        //
        mobact.clear();
        
        viewtable = new JTable();
        viewtable.invalidate();
        pane_canvas.setViewportView(viewtable);
        viewtable.setVisible(true);
    
        animetable = new JTable();
        animetable.invalidate();
        pane_fileList.setViewportView(animetable);
        animetable.setVisible(true);
    
    }                                      
    
    //export data button
    private void btn_exportMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // export data clicked
        File ex = new File(workplace + "/exports");
        if(!ex.exists())
            ex.mkdir();
        
        if(tables[0]!=null){
            String path = workplace +"/exports/log.xls";
            File x = new File(path);
            if(x.exists())
                x.delete();
            ExcelExporter ee = new ExcelExporter();
            try {            
                ee.exportTable(tables[0], x);
            } catch (IOException ex1) {
                JOptionPane.showMessageDialog(null, "failed to export table[0].", "System Message", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        if(tables[1]!=null){
            String path = workplace +"/exports/page_detail.xls";
            File x = new File(path);
            if(x.exists())
                x.delete();
            ExcelExporter ee = new ExcelExporter();
            try {            
                ee.exportTable(tables[1], x);
            } catch (IOException ex1) {
                JOptionPane.showMessageDialog(null, "failed to export table[1].", "System Message", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(tables[2]!=null){
        	String path = workplace +"/exports/user_detail.xls";
        	File x = new File(path);
        	if(x.exists())
                x.delete();
        	ExcelExporter ee = new ExcelExporter();
        	try {            
                ee.exportTable(tables[2], x);
            } catch (IOException ex1) {
                JOptionPane.showMessageDialog(null, "failed to export table[2].", "System Message", JOptionPane.ERROR_MESSAGE);
            }
        }
        if(tables[3]!=null){
        	String path = workplace +"/exports/mobile_events.xls";
        	File x = new File(path);
        	if(x.exists())
                x.delete();
        	ExcelExporter ee = new ExcelExporter();
        	try {            
                ee.exportTable(tables[3], x);
            } catch (IOException ex1) {
                JOptionPane.showMessageDialog(null, "failed to export table[3].", "System Message", JOptionPane.ERROR_MESSAGE);
            }
        }
    }                                       
    //read file button
    private void btn_readFileMouseClicked(java.awt.event.MouseEvent evt) {                                          
         //read file clicked
        try {
            getFileChooser();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "cannot open file chooser.", "System Message", JOptionPane.ERROR_MESSAGE);
        }
    }                                         
    //view table button
    private void btn_viewMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // view button clicked
        crossref();
        //inital table
        JTable viewtable = new JTable();
        viewtable.setEnabled(false);
        // set colume
        DefaultTableModel tableModel = (DefaultTableModel) viewtable.getModel();
        tableModel.setColumnCount(0);
        //set row
        tableModel.setRowCount(0);
        
        if(combox_graphic.getSelectedItem().equals("User")){
        	user.clear();
            if(reftable.isEmpty()){
                JOptionPane.showMessageDialog(null, "read in data first.", "System Message", JOptionPane.ERROR_MESSAGE);
            }else if(!reftable.isEmpty()){
            	for(int i=0; i<reftable.size(); i++){
            		String id = reftable.get(i).getid();
            		if(user.size() == 0){
            			userdetail ud = new userdetail(reftable.get(i).getid(), reftable.get(i).geturl());
            			user.add(ud);
            		}else {
            			for(int j=0; j<user.size(); j++){
            				if(user.get(j).getid().equals(id)){
            					user.get(j).chklist(reftable.get(i).geturl());
            					break;
            				}else if(j==user.size()-1 && !user.get(j).getid().equals(id)) {
            					userdetail ud = new userdetail(reftable.get(i).getid(), reftable.get(i).geturl());
            					user.add(ud);
            					break;
            				}
            			}
            		}
            	}
            }//end of if
            /*
            for(int k=0 ; k<user.size() ; k++){
                System.out.println(user.get(k).getid() + " " + user.get(k).getpageview() + " " + user.get(k).getindvpage() + " " + user.get(k).getmostview());
            }
            */
            String[] id = new String[user.size()];
            String[] pageview = new String[user.size()];
            String[] indv = new String[user.size()];
            String[] mostview = new String[user.size()];
            String[] mostnum = new String[user.size()];
            
            for(int i=0; i<user.size(); i++){
            	id[i] = user.get(i).getid();
            	pageview[i] = Integer.toString(user.get(i).getpageview());
            	indv[i] = Integer.toString(user.get(i).getindvpage());
            	mostview[i] = user.get(i).getmostview();
            	mostnum[i] = Integer.toString(user.get(i).getmostnum());
            }
            tableModel.setRowCount(user.size());
            tableModel.addColumn("User ID", id);
            tableModel.addColumn("Page Viewed", pageview);
            tableModel.addColumn("Unique Page Viewed", indv);
            tableModel.addColumn("Most Viewed", mostview);
            tableModel.addColumn("Most Viewed Times", mostnum);
            //update table
            tables[2] = viewtable;
            viewtable.invalidate();
            pane_canvas.setViewportView(viewtable);
            viewtable.setVisible(true);
        }//end of user
        else if(combox_graphic.getSelectedItem().equals("Webpage")){
            if(reftable.isEmpty()){
                JOptionPane.showMessageDialog(null, "read in data first.", "System Message", JOptionPane.ERROR_MESSAGE);
            }else if(!reftable.isEmpty()){
            	page.clear();
                for(int i=0 ; i<reftable.size() ; i++){
                    String table = reftable.get(i).geturl();
                    if(page.size() == 0){
                        pagedetail pd =new pagedetail(reftable.get(i).geturl(), reftable.get(i).getid());
                        page.add(pd);
                    }else{
                        for(int j=0 ; j<page.size() ; j++){
                            String pagename = page.get(j).geturl();
                            boolean b = pagename.equals(table);
                            if(b==true){
                                page.get(j).chkuser(reftable.get(i).getid());
                                break;
                            }else if(j==(page.size()-1) && b == false){
                                pagedetail pd =new pagedetail(reftable.get(i).geturl(), reftable.get(i).getid());
                                page.add(pd);
                                break;
                            }
                        }
                    }
                }
            }
            //table webpage
            /*
            for(int k=0 ; k<page.size() ; k++){
                //System.out.println(page.get(k).geturl() + " " + page.get(k).getacc() + " " + page.get(k).getindiv());
            }
            */ 
            //create table

            String num[] = new String[page.size()];
            String urls[] = new String[page.size()];
            String pvs[] = new String[page.size()];
            String idvs[] = new String[page.size()];

            for(int i=0 ; i<page.size() ; i++){
                num[i] = Integer.toString(i+1);
                urls[i] = page.get(i).geturl();
                pvs[i] = Integer.toString(page.get(i).getacc());
                idvs[i] = Integer.toString(page.get(i).getindiv());
            }
            tableModel.setRowCount(page.size());
            tableModel.addColumn("No", num);
            tableModel.addColumn("Url", urls);
            tableModel.addColumn("Page View", pvs);
            tableModel.addColumn("Individual Access", idvs);
            //update table
            tables[1] = viewtable;
            viewtable.invalidate();
            pane_canvas.setViewportView(viewtable);
            viewtable.setVisible(true);
        }//end of if web page 
        else if(combox_graphic.getSelectedItem().equals("Log")){
            if(reftable.isEmpty()){
                JOptionPane.showMessageDialog(null, "read in data first.", "System Message", JOptionPane.ERROR_MESSAGE);
            }
            //log.get(i).getuserid(), log.get(i).getuserip(), log.get(i).geturl(), log.get(i).gettime(), "", ""
           
            // add inital 3 columes
            String num[] = new String[reftable.size()];
            String ids[] = new String[reftable.size()];
            String urls[] = new String[reftable.size()];
            String times[] = new String[reftable.size()];
            for(int i=0 ; i<reftable.size() ; i++){
                num[i] = Integer.toString(i+1);
                ids[i] = reftable.get(i).getid();
                urls[i] = reftable.get(i).geturl();
                times[i] = reftable.get(i).gettimeformat();
            }
            tableModel.addColumn("No", num);
            tableModel.addColumn("User ID", ids);
            tableModel.addColumn("Url", urls);
            tableModel.addColumn("Access time", times);
            //add ip columes
            if(ck_ip.isSelected()){
                String ips[] = new String[reftable.size()];
                for(int i=0 ; i<reftable.size() ; i++){
                    ips[i] = reftable.get(i).getip();
                }
                tableModel.addColumn("user IP", ips);
            }
            //add browser colume
            if(ck_bt.isSelected()){
                String bss[] = new String[reftable.size()];
                for(int i=0 ; i<reftable.size() ; i++){
                    bss[i] = reftable.get(i).getsoft();
                }
                tableModel.addColumn("Browser", bss);
            }
            //add system colume
            if(ck_st.isSelected()){
                String sss[] = new String[reftable.size()];
                for(int i=0 ; i<reftable.size() ; i++){
                    sss[i] = reftable.get(i).getsys();
                }
                tableModel.addColumn("System", sss);
            }
            //update table
            tables[0] = viewtable;
            viewtable.invalidate();
            pane_canvas.setViewportView(viewtable);
            viewtable.setVisible(true);
           /*
            for(int s=0; s < tableModel.getRowCount() ; s++){
                System.out.println((String)tableModel.getValueAt(s, 0) + " " + (String)tableModel.getValueAt(s, 1) + " " + (String)tableModel.getValueAt(s, 2)
                        + " " + (String)tableModel.getValueAt(s, 4));
            }
            */ 
        }//end of log
        else if(combox_graphic.getSelectedItem().equals("User Act")){
        	if(reftable.isEmpty()){
                JOptionPane.showMessageDialog(null, "read in data first.", "System Message", JOptionPane.ERROR_MESSAGE);
            }else if(mobact.size()!=0){
            	mobtab.clear();
            	for(int i=0; i<mobact.size(); i++){
            		for(int j=0; j<reftable.size(); j++){
            			long mobtime = Long.parseLong(mobact.get(i).gettime());
            			long reftime = Long.parseLong(reftable.get(j).gettime());
            			long tem = Math.abs(mobtime-reftime);
            			if(tem<10 && mobact.get(i).getid().equals(reftable.get(j).getid())){
            				//userid; time; action; message; url; system; soft;
            				mobiletab mt = new mobiletab(mobact.get(i).getid(), mobact.get(i).gettime(), mobact.get(i).getact(), mobact.get(i).getmsg(), reftable.get(j).geturl(), reftable.get(j).getsys(), reftable.get(j).getsoft());
            				mt.changetime();
            				mobtab.add(mt);
            			}
            		}
            	}
            }
        	String[] id = new String[mobtab.size()];
            String[] time = new String[mobtab.size()];
            String[] act = new String[mobtab.size()];
            String[] msg = new String[mobtab.size()];
            String[] url = new String[mobtab.size()];
            String[] sys = new String[mobtab.size()];
            String[] soft = new String[mobtab.size()];
            
            for(int i=0; i<mobtab.size(); i++){
            	id[i] = mobtab.get(i).getid();
            	time[i] = mobtab.get(i).gettimeformat();
            	act[i] = mobtab.get(i).getact();
            	msg[i] = mobtab.get(i).getmsg();
            	url[i] = mobtab.get(i).geturl();
            	sys[i] = mobtab.get(i).getsys();
            	soft[i] = mobtab.get(i).getsoft();
            }
            tableModel.setRowCount(mobtab.size());
            tableModel.addColumn("User ID", id);
            tableModel.addColumn("Time", time);
            tableModel.addColumn("Action", act);
            tableModel.addColumn("Message", msg);
            tableModel.addColumn("URL", url);
            tableModel.addColumn("System", sys);
            tableModel.addColumn("Browser", soft);
            //update table
            tables[3] = viewtable;
            viewtable.invalidate();
            pane_canvas.setViewportView(viewtable);
            viewtable.setVisible(true);
        }//end of mobile
    }                                     
    // top menu
    private void tpm1_menuItem2MouseClicked(java.awt.event.MouseEvent evt) {                                            
        System.exit(0);
    }                                           
    //enable check box on bottom panel
    private void combox_graphicItemStateChanged(java.awt.event.ItemEvent evt) {                                                
        if(!combox_graphic.getSelectedItem().equals("Log")){
            ck_ip.setEnabled(false);
            ck_bt.setEnabled(false);
            ck_st.setEnabled(false);
        }else{
            ck_ip.setEnabled(true);
            ck_bt.setEnabled(true);
            ck_st.setEnabled(true);
        }
    }                                                                                     
    //View image button
    private void btn_viewimageMouseClicked(java.awt.event.MouseEvent evt) {                                           
        int index = animetable.getSelectedRow();
        if(index != -1){
            if(animeimg[index] != null){
                JFrame f2 = new JFrame();
                
                ImageIcon ii = new ImageIcon(animeimg[index]);
                JLabel lb = new JLabel();
                lb.setIcon(ii);
                f2.add(lb);
                Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
                Dimension framesize = f2.getSize();
                framesize.height = screensize.height;
                framesize.width = screensize.width;
                f2.setSize(framesize);
                f2.setVisible(true);
            }
        }
    }                                          
    //end of Ui Design and listeners
    //deinfed function below
    //open file chooser
    public void getFileChooser(){
        
        FileNameExtensionFilter txtfilter = new FileNameExtensionFilter("*.txt", "txt");
        //FileNameExtensionFilter pngfilter = new FileNameExtensionFilter("*.png", "png");
        FileNameExtensionFilter zipfilter = new FileNameExtensionFilter("*.zip", "zip");
        
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fc.setAcceptAllFileFilterUsed(false);
        fc.setDialogTitle("Choose directory [USQ_DATA] or File");
        //filter txt and png
        //fc.setFileFilter(pngfilter);
        fc.setFileFilter(txtfilter);
        fc.setFileFilter(zipfilter);
        
        try{
            fc.setCurrentDirectory(new File(workplace));
        }catch(Exception e) {
            FileSystemView fsv = FileSystemView.getFileSystemView();
            wppath = fsv.getDefaultDirectory();
            File rd = new File(wppath.getAbsolutePath() + "/USQ_Reporter.txt");
            rd.delete();
            try {
                setDir();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "file not found.", "System Message", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "IOException when get file.", "System Message", JOptionPane.ERROR_MESSAGE);
            }
        }
        int returnVal = fc.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //if txt from zip, dont copy to old
            fromzip = false;
            if(!file.exists()) {
                JOptionPane.showMessageDialog(null, "file doesn't exist.", "System Message", JOptionPane.ERROR_MESSAGE);
            } else if(file.isDirectory()) {
                File files[] = file.listFiles();
                File old = new File(workplace + "/old");
                //create old folder
                if(!old.exists())old.mkdir();
                if(old.exists()&&old.isFile())old.mkdir();
                for(int i=0 ; i<files.length ; i++) {
                    if(files[i].isFile()) {
                        readFile(files[i]);
                        if(files[i].getName().equals("USQRecorders.txt"))
                            createSes(files[i]);
                    }
                }
                //delete read in dir
                for(int i=0 ; i<files.length ; i++){
                    boolean b =files[i].delete();
                    System.out.println(files[i].getAbsolutePath() + " " + b);
                }
                file.delete();   
            } else if (file.isFile()) {
                File old = new File(workplace + "/old");
                //create old folder
                if(old.exists()&&old.isFile())old.mkdir();
                if(!old.exists())old.mkdir();
                if(file.getName().endsWith(".zip")){fromzip=true;}else{fromzip=false;}
                readFile(file);
                if(file.getName().equals("USQRecorders.txt"))
                    createSes(file);
            }
            
            //delete read in file
            file.delete();
        }
    }
    //create session for android record
    //create animated image
    //@param f : read in file 
    public void createSes(File f){
        ArrayList list = new ArrayList();
        list.addAll(andrec);

        ArrayList<Image> im = new ArrayList<Image>();
        im.addAll(images);
        Image anime = null;
        if(!im.isEmpty()){
            File path = new File(workplace+"/gifs");
            if(!path.exists())
                path.mkdir();
            String str = "/gifs/"+getFileTime(f)+".gif";
            str = str.replace(" ", "_");
            str = str.replace(":", "-");
            str = workplace + str;
            File gif = new File(str);
            try {
                AnimatedGifEncoder e = new AnimatedGifEncoder();
                e.start(str);
                e.setDelay(1000);
                for(int i=0 ; i<im.size() ; i++){
                    BufferedImage bi = (BufferedImage)im.get(i);
                    e.addFrame(bi);
                }
                e.finish();
                anime = Toolkit.getDefaultToolkit().createImage(gif.getAbsolutePath());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "failed to create gif.", "System Message", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
                System.out.println(gif.getAbsolutePath());
                System.out.println(workplace);
            }
        }
        session se = null;
        if(anime == null) {
            se = new session(getFileTime(f).toString(), list, null);
        }else if(anime != null) {
            for(int i=0 ; i<100 ; i++){
                if(animeimg[i]==null){
                    animeimg[i] = anime;
                    break;
                }
            }
            se = new session(getFileTime(f).toString(), list, anime);
            //update anime list
            updateanime();
        }
        ses.add(se);
        andrec.clear();
        images.clear();
    }
    //read in file, called by getFileChooser()
    //@param f : read in file
    public void readFile(File f) {
        if(f.getName().endsWith(".txt")) {
            if(f.getName().equals("USQRecorders.txt")) {
                readAndTxt(f);     
                lab_android.setText("Android read in");
            }else if(f.getName().equals("mdl_log.txt")) {
                readModLog(f);
                lab_moodle.setText("Moodle read in");
            }else if(f.getName().equals("mdl_chat_messages.txt") || f.getName().equals("mdl_forum_posts.txt") || f.getName().equals("mdl_quiz_attempts.txt")) {
            	readtabs(f);
            }else{
                //illegal file name
                //JOptionPane.showMessageDialog(null, "only accept .txt file named 'USQRecorders.txt','mdl_log.txt','mdl_chat_messages.txt','mdl_forum_posts.txt' and 'mdl_quiz_attempts.txt'", "System Message", JOptionPane.ERROR_MESSAGE);
            }
            if(fromzip == false) {
                copyOldtxt(f);
            }
        } else if(f.getName().endsWith(".zip")) {
            if(f.getName().endsWith(".zip"))fromzip=true;
            readZip(f);
            copyOldtxt(f);
            //delete original
            File del = new File(workplace + "/temp/USQ_IMAGE");
            File dels[] = del.listFiles();
            for(int i=0 ; i<dels.length ; i++){
                dels[i].delete();
            }
            File tmp = new File(workplace + "/temp/USQ_IMAGE/");
            tmp.delete();
            tmp = new File(workplace + "/temp");
            tmp.delete();
            lab_android.setText("Android read in");
        } else if(f.getName().endsWith(".png")) {
            readImage(f);
        }
    }
    //called by readFile(), read in USQRecorders.txt
    //@param f : read in file
    public void readAndTxt(File f) {      
        //read android txt
        String str = new String();
        try {
            BufferedReader br = new BufferedReader(new FileReader(f.getAbsolutePath()));
            while((str = br.readLine()) != null){
                String info[] = str.split(" ");
                AndroidRec ar = new AndroidRec(info[0], info[1], info[2], info[3], info[4], info[5], info[6], info[7]);
                andrec.add(ar);
            }
            br.close();   
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "read Android text file failed.", "System Message", JOptionPane.ERROR_MESSAGE);
        }
    }
    //read in mdl_log.txt
    //@param f : read in file
    public void readModLog(File f){
        String str = new String();
        try{
            BufferedReader br = new BufferedReader(new FileReader(f.getAbsolutePath()));
            str = br.readLine();
            
            while((str = br.readLine()) != null){
                //str = str.replaceAll(";", "");
                String info[] = str.split(";");
                mod_log mlg = new mod_log(info[0].trim(), info[1].trim(), info[2].trim(), info[3].trim(), info[4].trim(), info[5].trim(), info[6].trim(), info[7].trim(), info[8].trim());
                log.add(mlg);
            }
            br.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "read moodle log file failed.", "System Message", JOptionPane.ERROR_MESSAGE);
        }
    }
    //read in Android image
    //@param f : read in file
    public void readImage(File f) {
        try {
            //JFrame f2 = new JFrame();
            images.add(ImageIO.read(f));
            //JLabel lb = new JLabel(new ImageIcon(images.get(0)));
            //f2.add(lb);
            //f2.setVisible(true);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "read image failed.", "System Message", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    // read in zip file
    //@param f : read in file
    public void readZip(File f) {
        try {
            unzip(f);
            File file = new File(workplace + "/temp/USQ_IMAGE");
            File old = new File(workplace + "/old");
            if(!old.exists())old.mkdir();
            if(old.exists()&&old.isFile())old.mkdir();
            File files[] = file.listFiles();
            for(int i=0 ; i<files.length ; i++){
                readFile(files[i]);
            }
            //new session
            createSes(f);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "read zip file failed.", "System Message", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    //String fileType = f.getName().substring(f.getName().lastIndexOf(".") + 1,f.getName().length()).toLowerCase();
    
    //called by readZip()
    //@param f : read in file
    public void unzip(File f) throws Exception {
        String destDir = workplace + "/temp/";
        File tmp = new File(destDir);
        if(!tmp.exists())tmp.mkdir();
        byte b[] = new byte [1024];
        int length;
        
        ZipFile zipFile;
        zipFile = new ZipFile(f);
        Enumeration enumeration = zipFile.entries();
        ZipEntry zipEntry = null ;
        OutputStream outputStream = null;
        InputStream inputStream = null;
        while (enumeration.hasMoreElements()) {
              zipEntry = (ZipEntry) enumeration.nextElement();
              File loadFile = new File(destDir + zipEntry.getName());
              if (zipEntry.isDirectory()) {
                  // 这段都可以不要，因为每次都貌似从最底层开始遍历的
                 loadFile.mkdirs();
              }else{
                  if (!loadFile.getParentFile().exists())
                     loadFile.getParentFile().mkdirs();
                  outputStream = new FileOutputStream(loadFile);
                  inputStream = zipFile.getInputStream(zipEntry);
                  while ((length = inputStream.read(b)) > 0)
                       outputStream.write(b, 0, length);
             }
        }
        outputStream.flush();
        outputStream.close();
        inputStream.close();
    }
    //read chat message, forum posts and quiz attempts
    //@param f : read in file
    public void readtabs(File f) {
    	String str = new String();
        try{
            BufferedReader br = new BufferedReader(new FileReader(f.getAbsolutePath()));
            str = br.readLine();
            
            while((str = br.readLine()) != null){
                //str = str.replaceAll(";", "");
                String info[] = str.split(";");
                if(f.getName().equals("mdl_chat_messages.txt")){
                	//chat message id; chatid; userid; groupid; system; message; timestamp;
                	mobileact ma = new mobileact(info[2].trim(), info[6].trim(), "Chat Message", info[5]);
                	mobact.add(ma);
                }else if(f.getName().equals("mdl_forum_posts.txt")){
                	//id; discussion; parent; userid; created; modified; mailed; subject; message; 
                	//messageformat; messagetrust; attachment; totalscore; mailnow; 
                	mobileact ma = new mobileact(info[3].trim(), info[5].trim(), "Forum Posts", info[8].trim());
                	mobact.add(ma);
                }else if(f.getName().equals("mdl_quiz_attempts.txt")){
                	//id; quiz; userid; attempt; uniqueid; layout; currentpage; 
                	//preview; state; timestart; timefinish; timemodified; timecheckstate; 
                	//sumgrades; needsupgradetonewqe; 
                	mobileact ma = new mobileact(info[2].trim(), info[11].trim(), "Attempt Quiz", info[8].trim());
                	mobact.add(ma);
                }
            }
            br.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "read moodle log file failed.", "System Message", JOptionPane.ERROR_MESSAGE);
        }
    }
    /*
    //read forum post
    public void readForumPost(File f) {
    	String str = new String();
        try{
            BufferedReader br = new BufferedReader(new FileReader(f.getAbsolutePath()));
            str = br.readLine();
            
            while((str = br.readLine()) != null){
                //str = str.replaceAll(";", "");
                String info[] = str.split(";");
                //id; chatid; userid; groupid; system; message; timestamp;
                mobileact ma = new mobileact(info[2].trim(), info[6].trim(), "ChatMessage", info[5]);
                mobact.add(ma);
            }
            br.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "read moodle log file failed.", "System Message", JOptionPane.ERROR_MESSAGE);
        }
    }
    */
    //old copy
    //@param f : read in file
    public void copyOldtxt(File f) {
        if(f.isFile()&&new File(workplace+"/old").exists()){
            String name = "";
            if(f.getName().endsWith(".txt")){
                name = getFileTime(f) + ".txt";
            }else if(f.getName().endsWith(".zip")){
                name = getFileTime(f) + ".zip";
            }
            name = name.replace(":", "-");
            File target = new File(workplace+"/old/"+ name);
            if(!target.exists()){
                BufferedInputStream bis = null;
                BufferedOutputStream bos = null;
                try{
                    bis = new BufferedInputStream(new FileInputStream(f));
                    bos = new BufferedOutputStream(new FileOutputStream(target));
                    byte[] b = new byte[1024 * 5];
                    int len;
                    while((len = bis.read(b)) != -1){
                        bos.write(b, 0, len);
                    }
                    bos.flush();
                    bos.close();
                    bis.close();
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, "file not found when backup.", "System Message", JOptionPane.ERROR_MESSAGE);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "IOException when backup.", "System Message", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }
    //@param f : read in file
    public Date getFileTime(File f){
         long time = f.lastModified();
         Calendar cd = Calendar.getInstance();
         cd.setTimeInMillis(time);
         return cd.getTime();
    }
    
    /*
     * Calendar c=Calendar.getInstance();
     * c.set(year,month,date,hour,minute,second);
     * long answer=c.getTimeMillis()/1000;
     * 
     * 
     * reference android session and mdl_log
     */
    public void crossref(){
        reftable = new ArrayList();
        if(!log.isEmpty() && ses.isEmpty()){
            for(int i=0 ; i<log.size() ; i++){
                all_log alg = new all_log(log.get(i).getuserid(), log.get(i).getuserip(), log.get(i).geturl(), log.get(i).gettime(), "", "");
                reftable.add(alg);
            }
        }else if(!ses.isEmpty() && log.isEmpty()) {
            for(int i=0 ; i<ses.size() ; i++){
                ArrayList<AndroidRec> ad = ses.get(i).getrec();
                for(int j=0 ; j<ad.size() ; j++) {
                    all_log alg = new all_log("unknow", "unknow", ad.get(j).geturl(), ad.get(j).gettime(), ad.get(j).getsystem(), ad.get(j).getsoft());
                    reftable.add(alg);
                }
            }
        }else if(!ses.isEmpty() && !log.isEmpty()){
            for(int i=0 ; i<log.size() ; i++){
                all_log alg = new all_log(log.get(i).getuserid(), log.get(i).getuserip(), log.get(i).geturl(), log.get(i).gettime(), "", "");
                reftable.add(alg);
            }

           
            
            for(int k=0 ; k<ses.size() ; k++) {
                ArrayList<usersort> sort = new ArrayList<usersort>();
                ArrayList userid = new ArrayList();    
                ArrayList<Integer> poss = new ArrayList(); 
                ArrayList<AndroidRec> ad = new ArrayList();
                ad.addAll(ses.get(k).getrec());
                
                for(int n=0 ; n<ad.size() ; n++){
                    long andtime = Long.parseLong(ad.get(n).gettime());
                    for(int t=0 ; t<reftable.size() ; t++){
                        long logtime = (Long.parseLong(reftable.get(t).gettime()))*1000;
                        if((logtime-andtime)>60000)
                            break;
                        if(Math.abs(andtime - logtime) <= 60000){
                            String andurl = ad.get(n).geturl();
                            String logurl = reftable.get(t).geturl();
                            if(andurl.equals(logurl)){
                            userid.add(reftable.get(t).getid());
                                poss.add(n);
                                poss.add(t);
                            }
                        }
                    }
                }
                //find correct in matches
               
                for(int i=0 ; i<userid.size() ; i++){
                    if(sort.isEmpty()){
                        usersort so = new usersort(userid.get(i).toString());
                        sort.add(so);
                    }
                    for(int j=0 ; j<sort.size() ; j++){    
                        if(userid.get(i).toString().equals(sort.get(j).getid())){
                            sort.get(j).accnum();
                        }else if(j==(sort.size()-1) && !userid.get(i).toString().equals(sort.get(j).getid())){
                            usersort so = new usersort(userid.get(i).toString());
                            sort.add(so);
                        }
                    }
                }
                String correctuser = "";
                int usernum = 0;
                for(int s=0 ; s<sort.size() ; s++){
                    if((sort.get(s).getnum())>usernum){
                        usernum = sort.get(s).getnum();
                        correctuser = sort.get(s).getid();
                    }
                }
                //
                
                //
                if(!ad.isEmpty()){
                    int del = 0;
                    for(int i=0 ; i<poss.size() ; i+=2){
                        if((reftable.get(poss.get(i+1))).getid().equals(correctuser)){
                            if(!ad.isEmpty()){
                                reftable.get(poss.get(i+1)).setsys(ad.get(poss.get(i)-del).getsystem());
                                reftable.get(poss.get(i+1)).setsoft(ad.get(poss.get(i)-del).getsoft());
                                int index = poss.get(i) - del;
                                ad.remove(index);
                                del = del + 1;
                            }
                        }
                    }
                }
                for(int i=0 ; i<ad.size() ; i++){
                    all_log alg = new all_log("unknow", "unknow", ad.get(i).geturl(), ad.get(i).gettime(), ad.get(i).getsystem(), ad.get(i).getsoft());
                    reftable.add(alg);
                }
                sort.clear();
            }
        }

        for(int i=0 ; i<reftable.size() ; i++){
            long sort = 0;
            if(reftable.get(i).gettime().length() == 13){
                sort = Long.parseLong(reftable.get(i).gettime());
            }else if (reftable.get(i).gettime().length() == 10){
                sort = Long.parseLong(reftable.get(i).gettime())*1000;
            }
            reftable.get(i).settime((new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date(sort))).toString());
            //System.out.println(reftable.get(i).toString());
            //System.out.println(reftable.size());
        }
    }//end of corssref
    
    //right side, animetion table
    public void updateanime(){
        animetable = new JTable();
        // set colume
        DefaultTableModel tableModel = (DefaultTableModel) animetable.getModel();
        tableModel.setColumnCount(0);
        //set row
        tableModel.setRowCount(animeimg.length);
        String[] animeno = new String[100];
        for(int i=0; i<animeimg.length; i++){
            if(animeimg[i]==null)
                break;
            animeno[i] = Integer.toString(i+1);
        }
        tableModel.addColumn("Available Images", animeno);
        animetable.invalidate();
        pane_fileList.setViewportView(animetable);
        animetable.setVisible(true);
    }
    // check temp folder is correctly deleted
    public void tempcheck(){
    	//clear last data
        if(workplace!=null){
        	File temp = new File(workplace +"/temp");
        	if(temp.exists()){
        		File[] dels = temp.listFiles();
        		if(dels[0]!=null){
        			for(int i=0; i<dels.length; i++){
        				if(dels[i].isFile()){
        					dels[i].delete();
        				}else{
        					File[] delss = dels[i].listFiles();
        					if(delss[0]!=null){
        						for(int k=0; k<delss.length; k++){
        							delss[k].delete();
        						}
        					}
        					dels[i].delete();
        				}
        			}
        		}
        	}
        	temp.delete();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame = new mainFrame();
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                Dimension frameSize = frame.getSize();
                if (frameSize.height > screenSize.height){
                    frameSize.height = screenSize.height;
                }
                if (frameSize.width > screenSize.width){
                    frameSize.width = screenSize.width;
                }
                frame.setLocation((screenSize.width - frameSize.width) / 2,
                    (screenSize.height - frameSize.height) /2 );
                frame.setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify                     
    private javax.swing.JTable animetable;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_export;
    private javax.swing.JButton btn_readFile;
    private javax.swing.JButton btn_view;
    private javax.swing.JButton btn_viewimage;
    private javax.swing.JCheckBox ck_bt;
    private javax.swing.JCheckBox ck_ip;
    private javax.swing.JCheckBox ck_st;
    private javax.swing.JComboBox combox_graphic;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel lab_android;
    private javax.swing.JLabel lab_fileState;
    private javax.swing.JLabel lab_graphic;
    private javax.swing.JLabel lab_moodle;
    private javax.swing.JPanel pane_buttons;
    private javax.swing.JScrollPane pane_canvas;
    private javax.swing.JScrollPane pane_fileList;
    private javax.swing.JPanel pane_fileState;
    private javax.swing.JPanel pane_graphic;
    private javax.swing.JMenuBar topMenuBar;
    private javax.swing.JMenu topMenu_1;
    private javax.swing.JMenu tpm1_menuItem2;
    // End of variables declaration                   

}

class AndroidRec {
    private String url;
    private String year;
    private String month;
    private String day;
    private String time;
    private String deviceid;
    private String system;
    private String soft;
    
    public AndroidRec(String urlin, String yearin, String monthin, String dayin, String timein, String idin, String systemin, String softin){
        url = urlin;
        year = yearin;
        month = monthin;
        day = dayin;
        time = timein;
        deviceid = idin;
        system = systemin;
        soft = softin;
    }
    
    public String geturl(){
        return url;
    }
    public String getsystem(){
        return system;
    }
    public String getsoft(){
        return soft;
    }
    public String gettime(){
        long re = 0;
        try{
            String[] str = time.split(":");
            Calendar c = Calendar.getInstance();
            c.set(Integer.parseInt(year), Integer.parseInt(month)-1, Integer.parseInt(day), Integer.parseInt(str[0]), Integer.parseInt(str[1]), Integer.parseInt(str[2]));
            re = c.getTimeInMillis();
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Exception when processing time variable in AndroidRec.", "System Message", JOptionPane.ERROR_MESSAGE);
        }
        if(re == 0)
            JOptionPane.showMessageDialog(null, "Return a 0 time variable in AndroidRec.", "System Message", JOptionPane.ERROR_MESSAGE);
        return Long.toString(re);
    }
}

class session {
    private String id;
    private ArrayList ses_andlist;
    private Image ses_pngs;
    
    public session(String idin, ArrayList rcdin, Image pngin) {
        id = idin;
        ses_andlist = rcdin;
        ses_pngs = pngin;
    }
    
    public String getid() {
        return id;
    }
    public ArrayList getrec(){
        return ses_andlist;
    }
}

class mod_log {
    private String logid;
    private String time;
    private String userid;
    private String userip;
    private String course;
    private String mod;
    private String cmid;
    private String action;
    private String url;
    private String info;
    
    public mod_log(String logidin, String timein, String useridin, String ipin, String coursein, String modin, String cmidin, String actin, String urlin){
        logid = logidin;
        time = timein;
        userid = useridin;
        userip = ipin;
        course = coursein;
        mod = modin;
        cmid = cmidin;
        action = actin;
        url = urlin;
        //info = infoin;
    }
    public String gettime(){
        return time;
    }
    public String getuserid(){
        return userid;
    }
    public String getuserip(){
        return userip;
    }
    public String geturl(){
        return url;
    }
}

class all_log{
    private String userid;
    private String userip;
    private String url;
    private String time;
    private String timeformat;
    private String system;
    private String soft;
    
    public all_log(String idin, String ipin, String urlin, String timein, String sysin, String softin){
        userid = idin;
        userip = ipin;
        url = urlin;
        time = timein;
        timeformat = "";
        system = sysin;
        soft = softin;
    }
    
    public String getid(){
        return userid;
    }
    public String geturl(){
        return url;
    }
    public String gettime(){
        return time;
    }
    public String getsys(){
        return system;
    }
    public String getip(){
        return userip;
    }
    public String getsoft(){
        return soft;
    }
    public String gettimeformat(){
        return timeformat;
    }
    public void setsys(String sys){
        system = sys;
    }
    public void setsoft(String sf){
        soft = sf;
    }
    public void settime(String tm){
        timeformat = tm;
    }
    public String toString(){
        String str = userid + " " + userip + " " + url + " " + timeformat + " " + system + " " + soft;
        return str;
    }
}

class pagedetail{
    private String url;
    private int pageacc;
    private int indiv;
    private ArrayList<String> users  = new ArrayList();;
    
    public pagedetail(String urlin, String userid){
        url = urlin;
        pageacc = 1;
        indiv = 1;
        users.add(userid);
    }
    
    public void chkuser(String userid){
        for(int i=0; i<users.size() ; i++){
            if(users.get(i).toString().equals(userid)){
                pageacc = pageacc + 1;
                break;
            }else if(i==users.size()-1 && !users.get(i).toString().equals(userid)){
                users.add(userid);
                pageacc = pageacc + 1;
                indiv = users.size();
            }
        }
    }
    
    
    public String geturl(){
        return url;
    }
    public int getacc(){
        return pageacc;
    }
    public int getindiv(){
        return indiv;
    }
}

class usersort{
    private String userid;
    private int num;
    
    public usersort(String id){
        userid = id;
        num = 1;
    }
    
    public String getid(){
        return userid;
    }
    public void accnum(){
        num = num + 1;
    }
    public int getnum(){
        return num;
    }
}

class userdetail{
	private String userid;
	private int pageview;
	private int indvpage;
	private String mostviewurl;
	private ArrayList<String> userviewpage = new ArrayList<String>();
	private int mostviewnum;
	
	public userdetail(String id, String url){
		userid = id;
		pageview = 1;
		indvpage = 1;
		mostviewurl = url;
		mostviewnum = 1;
		userviewpage.add(url);
	}
	
	public String getid() {
		return userid;
	}
	public int getpageview() {
		return pageview;
	}
	public int getindvpage() {
		return indvpage;
	}
	public String getmostview() {
		return mostviewurl;
	}
	public int getmostnum() {
		return mostviewnum;
	}
	public void chklist(String url){
		pageview = pageview + 1;
		for(int i=0; i<userviewpage.size(); i++){
			if(url.equals(userviewpage.get(i))){
				//find same record dont increment indvpage
			}else if(i==userviewpage.size()-1 && url.equals(userviewpage.get(i))){
				//find new record
				indvpage = indvpage + 1;
			}
		}
		userviewpage.add(url);
		findmostview();
	}
	public void findmostview(){
		int num=0;
		int curnum =0;
		for(int i=0; i<userviewpage.size(); i++){
			for(int j=0; j<userviewpage.size(); j++){
				if(userviewpage.get(i).equals(userviewpage.get(j))){
					curnum = curnum + 1; 
				}
				if(curnum > num){
					num = curnum;
					mostviewurl = userviewpage.get(i);
				}
				if(j==userviewpage.size()-1){
					curnum = 0;
				}
			}
		}
		if(mostviewnum < num)
			mostviewnum = num;
	}
}

class mobileact{
	private String userid;
	private String time;
	private String action;
	private String message;
	
	public mobileact(String idin, String timein, String actionin, String messagein){
		userid = idin;
		time = timein;
		action = actionin;
		message = messagein;
	}
	public String getid(){
		return userid;
	}
	public String gettime(){
		return time;
	}
	public String getact(){
		return action;
	}
	public String getmsg(){
		return message;
	}
}

class mobiletab{
	private String userid;
	private String time;
	private String action;
	private String message;
	private String url;
	private String system;
	private String soft;
	private String timeformat;
	
	public mobiletab(String idin, String timein, String actionin, String messagein, String urlin, String sysin, String softin){
		userid = idin;
		time = timein;
		action = actionin;
		message = messagein;
		url = urlin;
		system = sysin;
		soft = softin;
		timeformat = "";
	}
	
	public String getid(){
		return userid;
	}
	public String gettime(){
		return time;
	}
	public String getact(){
		return action;
	}
	public String getmsg(){
		return message;
	}
	public String geturl(){
		return url;
	}
	public String getsys(){
		return system;
	}
	public String getsoft(){
		return soft;
	}
	public String gettimeformat(){
		return timeformat;
	}
	
	public void changetime(){
		long sort = 0;
        if(time.length() == 13){
            sort = Long.parseLong(time);
        }else if (time.length() == 10){
            sort = Long.parseLong(time)*1000;
        }
        timeformat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date(sort)).toString();
	}
}

class ExcelExporter {
    
    public ExcelExporter() { }
    public void setRow(){
        
    }
    public void exportTable(JTable table, File file) throws IOException {
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        FileWriter out = new FileWriter(file);
        for(int i=0; i < model.getColumnCount(); i++) {
            out.write(model.getColumnName(i) + "\t");
        }
        out.write("\n");
        
        try{
            for(int i=0; i< model.getRowCount(); i++) {
                for(int j=0; j < model.getColumnCount(); j++) {
                    out.write(model.getValueAt(i,j).toString()+"\t");
                }
            out.write("\n");
            }
        }catch(NullPointerException e){
            //do nothing
            out.close();
        }
        out.close();
        //System.out.println("write out to: " + file);
    }
}